### ISSUE TITLE
I want to add stations in a simplified format 

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-taf/conjoin#11]

**Comment by HansMJ** [comment]
Does stations here mean stations to the ICES station vocabulary / inputs to DOME or external data?

**Comment by neil-ices-dk** [comment]
yes - stations for inclusion in the station vocab;

**Comment by neil-ices-dk** [comment]
AMAP to clarify - the station text file in use is already quite simple, what did you have in mind?

**Comment by RobFryer** [comment]
I'm pretty sure this is about importing external data, some of which will relate to stations that are not in the ICES station dictionary.  For example, some of the Canadian data from the recent mercury assessment.  We currently have to files when we do this: the data file and a separate station file, which contains the stations that are not in the ICES dictionary.

**Comment by neil-ices-dk** [comment]
> I'm pretty sure this is about importing external data, some of which will relate to stations that are not in the ICES station dictionary. For example, some of the Canadian data from the recent mercury assessment. We currently have to files when we do this: the data file and a separate station file, which contains the stations that are not in the ICES dictionary.

thanks Rob - yes that is what we also understood related to AMAP data submissions. What is not clear from the document is if there is more to be done as there is already a simplified format/procedure for this, so we need Simon to clarify.
